#!/bin/bash

crontab -l |grep portal.sh >>/dev/null || {
    CRONDIR=$(cd "$(dirname "$0")"; pwd);
    TMPCRON=/tmp/curcrontab;
    crontab -l >$TMPCRON;
    echo "5 * * * * . /etc/profile; cd $CRONDIR; bash portal.sh;" >> $TMPCRON;
    crontab $TMPCRON;
    echo "crontab updated.";
}
