#!/bin/bash
TEMPDIR=/tmp/RIC

[ -d $TEMPDIR ] || mkdir $TEMPDIR
rm -rf $TEMPDIR/*

function clearRecord()
{
    [ $# -eq 0 ] && echo usage $0 host && exit 1;
    cat ~/.ssh/known_hosts|grep -v $1 >/tmp/known_hosts ;
    mv /tmp/known_hosts ~/.ssh
}

function csv2html ()
{
    awk -F";" 'NR>2{print "<td>" $1 "</td><td>" $3 "</td><td>" $9 "</td><td>" $11 "</td><td>" $4"-"$5 "</td></tr>" }'  $TEMPDIR/*_absrie.csv
    awk -F";" 'NR>2{print "<td>" $1 "</td><td>" $3 "</td><td>" $11 "</td><td>" $12 "</td><td>" $4"-"$5 "</td></tr>" }'  $TEMPDIR/*_abtrie.csv
    awk -F";" 'NR>2{print "<td>" $1 "</td><td>" $2 "</td><td>" $8 "</td><td>" $10 "</td><td>" $3"-"$4 "</td></tr>" }'  $TEMPDIR/*_atcrie.csv
    awk -F";" 'NR>2{print "<td>" $1 "</td><td>" $3 "</td><td>" $9 "</td><td>" $11 "</td><td>" $4"-"$5 "</td></tr>" }'  $TEMPDIR/*_amerie.csv;
#rm -rf $TEMPDIR/*csv;
}

function flush_RI ()
{
    curl -k -u axadmin:omc3 "https://$1/ensusm/ricgibin/eri.cgi?ensusm=ensusm&username=axadmin&action=Generate&equipment=bts&id=9";
    curl -k -u axadmin:omc3 "https://$1/ensusm/ricgibin/eri.cgi?ensusm=ensusm&username=axadmin&action=Generate&equipment=mfs&id=10";
    curl -k -u axadmin:omc3 "https://$1/ensusm/ricgibin/eri.cgi?ensusm=ensusm&username=axadmin&action=Generate&equipment=bsc&id=11";
    curl -k -u axadmin:omc3 "https://$1/ensusm/ricgibin/eri.cgi?ensusm=ensusm&username=axadmin&action=Generate&equipment=tc&id=12";
}

function ProcessRIFrom ()
{

#Flush
#    flush_RI $host >>/dev/null;
#scp to local
    clearRecord $host >>/dev/null;
    expect $(cd "$(dirname "$0")"; pwd)/scpFrom $host $TEMPDIR >>/dev/null;
#convert
    csv2html >>$TEMPDIR/raw.ri;
    cat $TEMPDIR/raw.ri|grep -v "???"|grep -v ERROR|grep -v Empty|grep -v "\-\-\-"|grep -v "<td></td>"|sed "s/^/\<tr\>\<td\>$host\<\/td\>/" >> currentnew.ri;
    rm $TEMPDIR/raw.ri;
}
