#!/bin/bash
[ -d $TEMPDIR ] || mkdir $TEMPDIR
rm -rf $TEMPDIR/*

function clearRecord()
{
    [ $# -eq 0 ] && echo usage $0 host && exit 1;
    cat ~/.ssh/known_hosts|grep -v $1 >/tmp/known_hosts ;
    mv /tmp/known_hosts ~/.ssh
}

function flush_RI ()
{
    curl -k -u axadmin:omc3 "https://$1/ensusm/ricgibin/eri.cgi?ensusm=ensusm&username=axadmin&action=Generate&equipment=bts&id=9";
    curl -k -u axadmin:omc3 "https://$1/ensusm/ricgibin/eri.cgi?ensusm=ensusm&username=axadmin&action=Generate&equipment=mfs&id=10";
    curl -k -u axadmin:omc3 "https://$1/ensusm/ricgibin/eri.cgi?ensusm=ensusm&username=axadmin&action=Generate&equipment=bsc&id=11";
    curl -k -u axadmin:omc3 "https://$1/ensusm/ricgibin/eri.cgi?ensusm=ensusm&username=axadmin&action=Generate&equipment=tc&id=12";
}
